# Generated by Django 5.2.3 on 2025-07-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='resources',
            field=models.ManyToManyField(related_name='services', to='booking.resource'),
        ),
    ]
