# Generated by Django 5.2.3 on 2025-06-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
