# Generated by Django 5.2.3 on 2025-06-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_timeslot_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='reservation',
            name='timeslot',
            field=models.ManyToManyField(to='booking.timeslot'),
        ),
    ]
