# Generated by Django 5.2.3 on 2025-07-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_servicetype_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
