# Generated by Django 5.2.3 on 2025-06-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_timeslot_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_stored',
            field=models.BooleanField(default=False),
        ),
    ]
