# Generated by Django 5.2.3 on 2025-07-26 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='booking.location'),
        ),
    ]
