# Generated by Django 5.2.3 on 2025-06-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation_is_stored'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='service',
        ),
    ]
