# Generated by Django 5.2.3 on 2025-07-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_reservation_timeslot_reservation_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
