# Generated by Django 5.2.3 on 2025-07-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_resource_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.location'),
        ),
    ]
